app_save_survey:
    path: /save_survey
    controller: App\Controller\SaveSurveyController::save
    methods: GET

app_get_survey:
    path: /get_survey
    controller: App\Controller\GetSurveyController::get
    methods: GET