app_save_survey:
    path: /save_survey
    controller: App\Controller\SurveyController::saveSurvey
    methods: GET

app_get_survey:
    path: /get_survey
    controller: App\Controller\SurveyController::getSurvey
    methods: GET